### ISSUE TITLE
errors and cpu spin on non-existent path

### ISSUE THREAD

**Issue by aadis** [rgrove/combohandler#2]
comboloader has been working great for me, for use with yui2 and yui3. Compared to the yui php combo loader, it works out of the box.

However I do see one problem. When the config includes a non-existent path comboloader goes into a spin, spewing out error messages along with high cpu use. This continues until I manually kill the process.

Including the logs:

<pre>
aaditya➜lib/node/combohandler(master✗)» spark2 -v                                                                                                                                                                                [13:31:01]
... starting
... detected config.js
... loading config `/usr/local/lib/node/.npm/combohandler/0.1.2/package/./config.js'
...   --roots { '/combo/static/vendor/lib/yui3': '/Users/aaditya/work/id/src/id/vaitarna/vaitarna/public/static/vendor/lib/3.4.0x',
  '/combo/static/vendor/lib/yui2': '/Users/aaditya/work/id/src/id/vaitarna/vaitarna/public/static/vendor/lib/2.9.0',
  '/combo/static/vendor/lib/epsilon': '/Users/aaditya/work/id/src/id/vaitarna/vaitarna/public/static/epsilon',
  '/combo/static/vendor/lib/d1/d2/gallery': '/Users/aaditya/work/id/src/id/vaitarna/vaitarna/public/static/vendor/lib/gallery',
  '/combo/2in3/static/vendor/lib/2in3': '/Users/aaditya/work/id/src/id/vaitarna/vaitarna/public/static/vendor/lib/2in3' }
... detected app.js
... starting with (1) workers
... child spawned 87224

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: ENOENT, No such file or directory '/Users/aaditya/work/id/src/id/vaitarna/vaitarna/public/static/vendor/lib/3.4.0x'
    at Object.lstatSync (fs.js:396:18)
    at Object.realpathSync (fs.js:627:23)
    at Object.combine (/usr/local/lib/node/.npm/combohandler/0.1.2/package/index.js:22:21)
    at /usr/local/lib/node/.npm/combohandler/0.1.2/package/lib/server.js:33:26
    at Object.<anonymous> (/usr/local/lib/node/.npm/combohandler/0.1.2/package/app.js:2:18)
    at Module._compile (module.js:407:26)
    at Object..js (module.js:413:10)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at require (module.js:351:19)
... Child Died (87224), respawning...
... child spawned 87225

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: ENOENT, No such file or directory '/Users/aaditya/work/id/src/id/vaitarna/vaitarna/public/static/vendor/lib/3.4.0x'
    at Object.lstatSync (fs.js:396:18)
    at Object.realpathSync (fs.js:627:23)
    at Object.combine (/usr/local/lib/node/.npm/combohandler/0.1.2/package/index.js:22:21)
    at /usr/local/lib/node/.npm/combohandler/0.1.2/package/lib/server.js:33:26
    at Object.<anonymous> (/usr/local/lib/node/.npm/combohandler/0.1.2/package/app.js:2:18)
    at Module._compile (module.js:407:26)
    at Object..js (module.js:413:10)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at require (module.js:351:19)
... Child Died (87225), respawning...
... child spawned 87226

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
</pre>

**Comment by rgrove** [comment]
The combohandler process is exiting with an error, which is the desired behavior in this case since it lets you know immediately that the config is invalid.

When spark2 sees the combohandler process die, it restarts it, since that's spark2's job. This results in an endless restart loop, but it's not a bug. Just fix the config and everything will be fine. :)
