### ISSUE TITLE
Documentation for root configuration file is incorrect

### ISSUE THREAD

**Issue by blicksky** [rgrove/combohandler#38]
The example root configuration file found at https://github.com/rgrove/combohandler#root-configuration does not seem to work. Instead, I had to provide a file without the nested `roots` object, such as:

```
{
    "/yui3": "/local/path/to/yui3"
}
```

**Comment by evocateur** [comment]
You are correct! I'll fix that momentarily.

**Comment by blicksky** [comment]
Thanks! You probably also want to update the documentation here: https://www.npmjs.org/package/combohandler#root-configuration

**Comment by evocateur** [comment]
Yep, as soon as I publish the next version, that will be updated. Thanks!
