### ISSUE TITLE
Ensure compatibility with Express 3.x

### ISSUE THREAD

**Issue by rgrove** [rgrove/combohandler#8]
Rumor has it Express 3.x and Combo Handler don't get along. Need to look into this.

**Comment by juandopazo** [comment]
What if you go a little more Express agnostic?

In the middleware you're doing `res.header('Last-Modified', lastModified.toUTCString());`. Could you use the native Node `res.setHeader` method?

**Comment by rgrove** [comment]
Just committed Express 3.0 support. I'll consider looking into being more generic later, but it's not a high priority.
